---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Values.env }}-data
  namespace: {{ .Values.env }}
  labels:
    version: {{ .Values.app.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.env }}-data
  replicas: {{ .Values.data.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-data
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: data
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command:
          - ./app
          - "-role"
          - "data"
          - "-server"
          - {{ .Values.env }}-{{ .Values.nats.service.name }}
        env:
          - name: APP_DB
            value: "root@tcp({{ .Values.env }}-{{ .Values.mysql.service.name }}:3306)/demo"
          - name: APP_CACHE
            value: "{{ .Values.env }}-{{ .Values.redis.service.name }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.data.port }}
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.data.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: {{ .Values.data.port }}
          initialDelaySeconds: 0
          periodSeconds: 3
