---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Values.env }}-img
  namespace: {{ .Values.env }}
  labels:
    version: {{ .Values.app.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.env }}-img
  replicas: {{ .Values.img.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-img
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: img
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command:
          - ./app
          - "-role"
          - "img"
          - "-r"
          - "0.2"
          - "-server"
          - {{ .Values.env }}-{{ .Values.nats.service.name }}
        imagePullPolicy: Always
        env:
          - name: APP_CACHE
            value: "{{ .Values.env }}-{{ .Values.redis.service.name }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.img.port }}
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.img.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: {{ .Values.img.port }}
          initialDelaySeconds: 0
          periodSeconds: 3